name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  check-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: make init
      # - name: Check type
      #   run: make type
      - name: Check Lint
        run: make lint
      - name: Test
        run: make test
